<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 /Users/ming/Desktop/app/src/assets/models/nekocom.gltf --transformmm
-->
<script lang="ts">
  import { BoxGeometry, Group, Object3D, PointLight, PointLightHelper, RectAreaLight, Vector3 } from 'three'
  import { T, useThrelte } from '@threlte/core'
	import { useGltf } from '@threlte/extras';
	import { AutoColliders, CollisionGroups, RigidBody } from '@threlte/rapier';
  import { cam, controls } from '$lib/stores';
	import { PolyhedronFactory } from './Factory';
	import { mat_bulb, mat_glass, mat_nekocom_connectors, mat_pink } from './Materials';
  import {RectAreaLightHelper} from "three/examples/jsm/helpers/RectAreaLightHelper";
  import { RectAreaLightUniformsLib } from 'three/examples/jsm/lights/RectAreaLightUniformsLib'
	
  // init rect light 
	RectAreaLightUniformsLib.init()

	const { gltf } = useGltf('src/assets/models/nekocom.gltf')
  const { scene } = useThrelte()
  
  // light helper
  let comLight: PointLight
  // light helper
  let panelLight: RectAreaLight
  $:{
    if(scene && comLight){
      scene.add(new PointLightHelper(comLight,1))
    }
  }
  $:{
    if(scene && panelLight){
      panelLight.add(new RectAreaLightHelper(panelLight))
    }
  }

	const {camera} = useThrelte()
	$:{
		if($gltf && $camera){
      let obj = new Object3D().getObjectByName("nekocom")
      if(obj){
        $camera.lookAt(obj.getWorldPosition(new Vector3()))
			  $cam.expectedRotation = [$camera.rotation.x,$camera.rotation.y,$camera.rotation.z]
      }
		}
	}

	let comPos:[x: number, y: number, z: number] = [0,0,0]
</script>

{#if $gltf}

<CollisionGroups groups={[0, 15]}>
	<RigidBody type={"fixed"}>
		<AutoColliders shape={'trimesh'}>
      <T.Group  {...$$restProps}>
        <T.Group position={comPos} scale={3} rotation={[0,Math.PI,0]} name={"nekocom"}>
          <!-- GLTF -->
          <T.Group>
            <T.Mesh receiveShadow castShadow geometry={$gltf.nodes.monitor.geometry} material={$gltf.materials.monitor} />
            <!-- <T.Mesh receiveShadow castShadow geometry={$gltf.nodes.monitor.geometry} material={mat} /> -->
            <T.Mesh castShadow geometry={$gltf.nodes.tail.geometry} material={$gltf.materials.tail} position={[-1.13, -0.66, 0.6]} />
            <T.Mesh castShadow     
              geometry={$gltf.nodes.tail_connector.geometry}
              material={mat_nekocom_connectors}
              position={[-0.03, -1.21, 0.39]}
            />
            <T.Mesh castShadow geometry={$gltf.nodes.ear_band.geometry}
              material={$gltf.materials['ear connector']}
              position={[0.01, 0.84, -0.19]}
            />
            <T.Group position={[-0.77, 1.42, -0.43]} rotation={[-1.52, 1.16, 1.71]}>
              <T.Mesh castShadow geometry={$gltf.nodes.Cube002.geometry} material={$gltf.materials['inside ear']} />
              <T.Mesh castShadow geometry={$gltf.nodes.Cube002_1.geometry} material={$gltf.materials['outside ear']} />
            </T.Group>
            <T.Group position={[0.72, 1.42, -0.43]} rotation={[-1.52, -1.16, -1.71]}>
              <T.Mesh castShadow geometry={$gltf.nodes.Cube004.geometry} material={$gltf.materials['inside ear']} />
              <T.Mesh castShadow geometry={$gltf.nodes.Cube004_1.geometry} material={$gltf.materials['outside ear']} />
            </T.Group>
            <T.Mesh castShadow geometry={$gltf.nodes.left_paw.geometry} material={$gltf.materials.paw} position={[-0.56, -1.31, -0.74]} />
            <T.Mesh castShadow geometry={$gltf.nodes.right_paw.geometry} material={$gltf.materials.paw} position={[0.58, -1.31, -0.74]} />
            <T.Mesh
              geometry={$gltf.nodes.paw_connector_right.geometry}
              material={$gltf.materials["connector"]}
              position={[0.55, -1.21, -0.43]} castShadow/>
            <T.Mesh castShadow geometry={$gltf.nodes.paw_connector_left.geometry}
              material={$gltf.materials["connector"]}
              position={[-0.59, -1.21, -0.43]}
            />
          </T.Group>

          <T.Mesh position={[0,0,-0.8]} geometry={new BoxGeometry(1.6,1.6,0.1)} material={mat_glass}>
            <T.RectAreaLight power={500} position={[0,0,0]} width={5} height={5} intensity={$controls.com.intensity} rotation={[0,Math.PI,0]}/>
            <T.RectAreaLight power={500} position={[0,0,0]} width={5} height={5} intensity={$controls.com.intensity} rotation={[0,0,0]}/>
          </T.Mesh>
        </T.Group>
      </T.Group>
		</AutoColliders>
	</RigidBody>
</CollisionGroups>

<CollisionGroups groups={[0]}>
	<RigidBody>
		<AutoColliders>
			<T.Mesh scale={0.2} receiveShadow castShadow geometry={PolyhedronFactory.getRand()} material={mat_pink} position={comPos}></T.Mesh>
		</AutoColliders>
	</RigidBody>
	<RigidBody>
		<AutoColliders>
      <T.Mesh position={[0,-0.6,0]} geometry={new BoxGeometry(1,1,1)} material={mat_bulb}>
        <!-- <T.PointLight power={1000} distance={$controls.com.distance} intensity={$controls.com.intensity} bind:ref={comLight}></T.PointLight> -->
      </T.Mesh>
    </AutoColliders>
  </RigidBody> 
</CollisionGroups>
{/if}