<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\blends\planet\planet.gltf --transform -k
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

	const gltfUrl = new URL('$src/assets/models/planet/planet.glb', import.meta.url).href
  const { gltf } = useGltf(gltfUrl, { useDraco: true })
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="planet"
      geometry={$gltf.nodes.planet.geometry}
      material={$gltf.materials.grassside}
      position={[0,0,0]}
    />
    <slot {ref} />
  </Three>
{/if}
