<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\moon\moon.glb -t --transform
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group, Mesh, Vector3 } from 'three'
  import { T, Three, type Props, type Events, type Slots, useFrame } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
	import Model from './Model.svelte';

  export const ref = new Group()
  export let rotateOrigin: [x:number,y:number,z:number] = [0,0,0]
  export let pos: [x:number,y:number,z:number] = [0,0,0]
  export let orbit = false
  let obj: Group
  let innerObj: Group
  $:{
    if(obj){
      obj.traverse((child)=>{
        child.castShadow = true
        child.receiveShadow = true
      })
    }
  }
  useFrame((_,delta)=>{
    update(delta)
	})

	function update(delta: number){
    let scale = 1000*delta
		if(orbit && obj && innerObj){
      obj.rotateOnAxis(new Vector3(0,1,0),0.0001*scale)
      innerObj.rotateOnAxis(new Vector3(0,1,0),0.0005*scale)
    }
	}
</script>
<Model bind:obj={obj} bind:innerObj={innerObj} pos={pos} rotateOrigin={rotateOrigin} {...$$restProps}/>
