<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\moon\moon.glb -t --transform
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group, Vector3 } from 'three'
  import { T, Three, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()
  export let rotateOrigin: [x:number,y:number,z:number] = [0,0,0]
  export let pos: [x:number,y:number,z:number] = [0,0,0]
  
  let computedOrigin = pos.map((x,i) => x - rotateOrigin[i]) as [x:number,y:number,z:number]
  type GLTFResult = {
    nodes: {
      Icosphere_1: THREE.Mesh
      Icosphere_2: THREE.Mesh
    }
    materials: {
      light: THREE.MeshStandardMaterial
      dark: THREE.MeshStandardMaterial
    }
  }

	const gltfUrl = new URL('$src/assets/models/moon/moon.glb', import.meta.url).href
  const { gltf } = useGltf<GLTFResult>(gltfUrl, { useDraco: true })
</script>

{#if $gltf}
  <Three position={rotateOrigin} type={ref} {...$$restProps}>
    <T.Group position={computedOrigin} scale={7}>
      <T.Mesh geometry={$gltf.nodes.Icosphere_1.geometry} material={$gltf.materials.light} />
      <T.Mesh geometry={$gltf.nodes.Icosphere_2.geometry} material={$gltf.materials.dark} />
      <slot {ref} />
    </T.Group>
  </Three>
{/if}
