<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 /Users/ming/Desktop/app/src/assets/models/nekocom.gltf --transformmm
-->
<script lang="ts">
  import { BoxGeometry, Group, Mesh, Object3D, PointLight, PointLightHelper, RectAreaLight, Vector3 } from 'three'
  import { InteractiveObject, T, useThrelte } from '@threlte/core'
	import { AutoColliders, CollisionGroups, RigidBody } from '@threlte/rapier';
	import { PolyhedronFactory } from '../Factory';
	import { mat_bulb, mat_glass, mat_pink } from './Materials';
	import Model from './model.svelte';
	import Panel from './Panel.svelte';
	import { controls } from '$lib/stores';
	
	export let comPos:[x: number, y: number, z: number] = [0,0,0]
  	export let obj: Group

	let panel: Mesh
	function screenSwitch(){
		$controls.com.intensity = $controls.com.intensity == 0 ? 10 : 0
	}
</script>


<CollisionGroups groups={[0, 15]}>
	<Model bind:obj={obj} pos={comPos} rigidBodyType={"fixed"}>
    	<Panel bind:panel={panel}></Panel>
  	</Model>
</CollisionGroups>

<CollisionGroups groups={[0]}>
	<RigidBody>
		<AutoColliders>
			<T.Mesh scale={0.2} receiveShadow castShadow geometry={PolyhedronFactory.getRand()} material={mat_pink} position={comPos}></T.Mesh>
		</AutoColliders>
	</RigidBody>
	<RigidBody>
		<AutoColliders>
      <T.Mesh position={[0,-0.6,0]} geometry={new BoxGeometry(0.3,0.3,0.3)} material={mat_bulb}>
      </T.Mesh>
    </AutoColliders>
  </RigidBody> 
</CollisionGroups>

<T.Mesh position={[5,10,-20]} let:ref geometry={PolyhedronFactory.getRand()} material={mat_pink}>
	<InteractiveObject interactive object={ref} on:pointerleave={()=>document.documentElement.style.cursor = 'default'} on:pointerenter={()=>document.documentElement.style.cursor = 'pointer'} on:click={()=>screenSwitch()}/>
</T.Mesh>