<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 /Users/ming/Desktop/app/src/assets/models/nekocom.gltf --transformmm
-->
<script lang="ts">
  import { BoxGeometry, Group, Object3D, PointLight, PointLightHelper, RectAreaLight, Vector3 } from 'three'
  import { T, useThrelte } from '@threlte/core'
	import { AutoColliders, CollisionGroups, RigidBody } from '@threlte/rapier';
	import { PolyhedronFactory } from '../Factory';
	import { mat_bulb, mat_glass, mat_nekocom_connectors, mat_pink } from '../Materials';
	import Model from './model.svelte';
	import Panel from './Panel.svelte';
	
	export let comPos:[x: number, y: number, z: number] = [0,0,0]
  	export let obj: Group
</script>


<CollisionGroups groups={[0, 15]}>
	<Model bind:obj={obj} pos={comPos} rigidBodyType={"fixed"}>
    <Panel></Panel>
  </Model>
</CollisionGroups>

<CollisionGroups groups={[0]}>
	<RigidBody>
		<AutoColliders>
			<T.Mesh scale={0.2} receiveShadow castShadow geometry={PolyhedronFactory.getRand()} material={mat_pink} position={comPos}></T.Mesh>
		</AutoColliders>
	</RigidBody>
	<RigidBody>
		<AutoColliders>
      <T.Mesh position={[0,-0.6,0]} geometry={new BoxGeometry(0.3,0.3,0.3)} material={mat_bulb}>
      </T.Mesh>
    </AutoColliders>
  </RigidBody> 
</CollisionGroups>