<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\planet\planet.gltf -k
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const { gltf } = useGltf('/planet.gltf')
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh name="Icosphere013" geometry={$gltf.nodes.Icosphere013.geometry} material={$gltf.materials.water} />
    <T.Mesh
      name="Icosphere013_1"
      geometry={$gltf.nodes.Icosphere013_1.geometry}
      material={$gltf.materials['deep water']}
    />
    <T.Mesh
      name="Icosphere013_2"
      geometry={$gltf.nodes.Icosphere013_2.geometry}
      material={$gltf.materials.deepdeepwater}
    />
    <T.Mesh name="Icosphere013_3" geometry={$gltf.nodes.Icosphere013_3.geometry} material={$gltf.materials.Snow} />
    <T.Mesh name="Icosphere013_4" geometry={$gltf.nodes.Icosphere013_4.geometry} material={$gltf.materials.semisnow} />
    <T.Mesh name="Icosphere013_5" geometry={$gltf.nodes.Icosphere013_5.geometry} material={$gltf.materials.grass} />
    <T.Mesh name="Icosphere013_6" geometry={$gltf.nodes.Icosphere013_6.geometry} material={$gltf.materials.grassside} />

    <slot {ref} />
  </Three>
{/if}
