<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\sakura2.gltf --transform -k
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

	const gltfUrl = new URL('$src/assets/models/trees/sakura2.gltf', import.meta.url).href
	const { gltf } = useGltf(gltfUrl,{useDraco:true})
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="sakuratree2_leaf"
      geometry={$gltf.nodes.sakuratree2_leaf.geometry}
      material={$gltf.nodes.sakuratree2_leaf.material}
      position={[1.64, 4.22, 4.42]}
    />
    <T.Mesh
      name="sakuratree2_leaf001"
      geometry={$gltf.nodes.sakuratree2_leaf001.geometry}
      material={$gltf.nodes.sakuratree2_leaf001.material}
      position={[2.05, 4.05, -2.33]}
    />
    <T.Mesh
      name="sakuratree2_leaf002"
      geometry={$gltf.nodes.sakuratree2_leaf002.geometry}
      material={$gltf.nodes.sakuratree2_leaf002.material}
      position={[-0.57, 3.49, 4.43]}
    />
    <T.Mesh
      name="sakuratree2_leaf003"
      geometry={$gltf.nodes.sakuratree2_leaf003.geometry}
      material={$gltf.nodes.sakuratree2_leaf003.material}
      position={[0.06, 7.66, -1.74]}
    />
    <T.Mesh
      name="sakuratree2_leaf004"
      geometry={$gltf.nodes.sakuratree2_leaf004.geometry}
      material={$gltf.nodes.sakuratree2_leaf004.material}
      position={[-3.47, 4.44, 1.6]}
    />
    <T.Mesh
      name="sakuratree2_leaf005"
      geometry={$gltf.nodes.sakuratree2_leaf005.geometry}
      material={$gltf.nodes.sakuratree2_leaf005.material}
      position={[1.35, 7.06, 4.26]}
    />
    <T.Mesh
      name="sakuratree2_leaf006"
      geometry={$gltf.nodes.sakuratree2_leaf006.geometry}
      material={$gltf.nodes.sakuratree2_leaf006.material}
      position={[-2.14, 6.36, 0.42]}
    />
    <T.Mesh
      name="sakuratree2_branch"
      geometry={$gltf.nodes.sakuratree2_branch.geometry}
      material={$gltf.nodes.sakuratree2_branch.material}
      position={[-0.06, 4.24, 0.15]}
    />
    <T.Mesh
      name="sakuratree2_branch003"
      geometry={$gltf.nodes.sakuratree2_branch003.geometry}
      material={$gltf.nodes.sakuratree2_branch003.material}
      position={[-0.42, 5.47, 1.66]}
    />
    <T.Mesh
      name="sakuratree2_branch004"
      geometry={$gltf.nodes.sakuratree2_branch004.geometry}
      material={$gltf.nodes.sakuratree2_branch004.material}
      position={[0.32, 5.8, 2.13]}
    />
    <T.Mesh
      name="sakuratree2_branch005"
      geometry={$gltf.nodes.sakuratree2_branch005.geometry}
      material={$gltf.nodes.sakuratree2_branch005.material}
      position={[0.34, 4.78, -0.02]}
    />
    <T.Mesh
      name="sakuratree2_branch006"
      geometry={$gltf.nodes.sakuratree2_branch006.geometry}
      material={$gltf.nodes.sakuratree2_branch006.material}
      position={[0.1, 3.69, 2.6]}
    />
    <T.Mesh
      name="sakuratree2_branch007"
      geometry={$gltf.nodes.sakuratree2_branch007.geometry}
      material={$gltf.nodes.sakuratree2_branch007.material}
      position={[-0.88, 5.17, 0.91]}
    />
    <T.Mesh
      name="sakuratree2_branch008"
      geometry={$gltf.nodes.sakuratree2_branch008.geometry}
      material={$gltf.nodes.sakuratree2_branch008.material}
      position={[-1.68, 4.63, 1.26]}
    />
    <T.Mesh
      name="sakuratree2_branch009"
      geometry={$gltf.nodes.sakuratree2_branch009.geometry}
      material={$gltf.nodes.sakuratree2_branch009.material}
      position={[0.88, 4.19, -0.38]}
    />
    <T.Mesh
      name="sakuratree2_branch010"
      geometry={$gltf.nodes.sakuratree2_branch010.geometry}
      material={$gltf.nodes.sakuratree2_branch010.material}
      position={[1.06, 4.12, 1.98]}
    />
    <T.Mesh
      name="sakuratree2_leaf007"
      geometry={$gltf.nodes.sakuratree2_leaf007.geometry}
      material={$gltf.nodes.sakuratree2_leaf007.material}
      position={[-1.69, 6.7, 3.4]}
    />
    <T.Mesh
      name="sakuratree2_leaf008"
      geometry={$gltf.nodes.sakuratree2_leaf008.geometry}
      material={$gltf.nodes.sakuratree2_leaf008.material}
      position={[1.39, 5.75, -1.47]}
    />
    <T.Mesh
      name="sakuratree2_branch002"
      geometry={$gltf.nodes.sakuratree2_branch002.geometry}
      material={$gltf.nodes.sakuratree2_branch002.material}
      position={[0.94, 4.18, 0.69]}
    />
    <T.Mesh
      name="sakuratree2_leaf009"
      geometry={$gltf.nodes.sakuratree2_leaf009.geometry}
      material={$gltf.nodes.sakuratree2_leaf009.material}
      position={[2.16, 4.87, 1.1]}
    />
    <T.Mesh
      name="sakuratree2_leaf010"
      geometry={$gltf.nodes.sakuratree2_leaf010.geometry}
      material={$gltf.nodes.sakuratree2_leaf010.material}
      position={[0.37, 6.49, 0.91]}
    />
    <T.Mesh
      name="sakuratree2_leaf011"
      geometry={$gltf.nodes.sakuratree2_leaf011.geometry}
      material={$gltf.nodes.sakuratree2_leaf011.material}
      position={[-1.52, 2.87, 2.85]}
    />
    <T.Mesh
      name="sakuratree2_branch001"
      geometry={$gltf.nodes.sakuratree2_branch001.geometry}
      material={$gltf.nodes.sakuratree2_branch001.material}
      position={[-0.17, 3.28, 2.27]}
    />

    <slot {ref} />
  </Three>
{/if}
