<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\sakura0.gltf --transform -k
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

	const gltfUrl = new URL('$src/assets/models/trees/sakura0.gltf', import.meta.url).href
	const { gltf } = useGltf(gltfUrl,{useDraco:true})
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="sakuratree0_leaf"
      geometry={$gltf.nodes.sakuratree0_leaf.geometry}
      material={$gltf.nodes.sakuratree0_leaf.material}
      position={[1.65, 4.01, 1.3]}
    />
    <T.Mesh
      name="sakuratree0_leaf001"
      geometry={$gltf.nodes.sakuratree0_leaf001.geometry}
      material={$gltf.nodes.sakuratree0_leaf001.material}
      position={[2.13, 4.17, -0.17]}
    />
    <T.Mesh
      name="sakuratree0_leaf002"
      geometry={$gltf.nodes.sakuratree0_leaf002.geometry}
      material={$gltf.nodes.sakuratree0_leaf002.material}
      position={[-0.39, 4.64, 2.25]}
    />
    <T.Mesh
      name="sakuratree0_leaf003"
      geometry={$gltf.nodes.sakuratree0_leaf003.geometry}
      material={$gltf.nodes.sakuratree0_leaf003.material}
      position={[-2, 5.66, -0.56]}
    />
    <T.Mesh
      name="sakuratree0_leaf004"
      geometry={$gltf.nodes.sakuratree0_leaf004.geometry}
      material={$gltf.nodes.sakuratree0_leaf004.material}
      position={[1.22, 5.47, -1.81]}
    />
    <T.Mesh
      name="sakuratree0_leaf005"
      geometry={$gltf.nodes.sakuratree0_leaf005.geometry}
      material={$gltf.nodes.sakuratree0_leaf005.material}
      position={[2.16, 5.78, 2.31]}
    />
    <T.Mesh
      name="sakuratree0_leaf006"
      geometry={$gltf.nodes.sakuratree0_leaf006.geometry}
      material={$gltf.nodes.sakuratree0_leaf006.material}
      position={[0.18, 5.96, -2.5]}
    />
    <T.Mesh
      name="sakuratree0_leaf007"
      geometry={$gltf.nodes.sakuratree0_leaf007.geometry}
      material={$gltf.nodes.sakuratree0_leaf007.material}
      position={[0.48, 6.9, 0.65]}
    />
    <T.Mesh
      name="sakuratree0_branch008"
      geometry={$gltf.nodes.sakuratree0_branch008.geometry}
      material={$gltf.nodes.sakuratree0_branch008.material}
      position={[1.33, 3.96, -0.07]}
    />
    <T.Mesh
      name="sakuratree0_branch001"
      geometry={$gltf.nodes.sakuratree0_branch001.geometry}
      material={$gltf.nodes.sakuratree0_branch001.material}
      position={[0.87, 4.08, 0.25]}
    />
    <T.Mesh
      name="sakuratree0_branch002"
      geometry={$gltf.nodes.sakuratree0_branch002.geometry}
      material={$gltf.nodes.sakuratree0_branch002.material}
      position={[-0.39, 3.62, 1.07]}
    />
    <T.Mesh
      name="sakuratree0_branch003"
      geometry={$gltf.nodes.sakuratree0_branch003.geometry}
      material={$gltf.nodes.sakuratree0_branch003.material}
      position={[-0.97, 4.2, -0.07]}
    />
    <T.Mesh
      name="sakuratree0_branch004"
      geometry={$gltf.nodes.sakuratree0_branch004.geometry}
      material={$gltf.nodes.sakuratree0_branch004.material}
      position={[1.23, 4.74, 1.13]}
    />
    <T.Mesh
      name="sakuratree0_branch005"
      geometry={$gltf.nodes.sakuratree0_branch005.geometry}
      material={$gltf.nodes.sakuratree0_branch005.material}
      position={[0.47, 4.27, -1.46]}
    />
    <T.Mesh
      name="sakuratree0_branch006"
      geometry={$gltf.nodes.sakuratree0_branch006.geometry}
      material={$gltf.nodes.sakuratree0_branch006.material}
      position={[-0.25, 4.24, -1.11]}
    />
    <T.Mesh
      name="sakuratree0_branch007"
      geometry={$gltf.nodes.sakuratree0_branch007.geometry}
      material={$gltf.nodes.sakuratree0_branch007.material}
      position={[0.63, 4.44, 1.34]}
    />
    <T.Mesh
      name="sakuratree0_branch"
      geometry={$gltf.nodes.sakuratree0_branch.geometry}
      material={$gltf.nodes.sakuratree0_branch.material}
      position={[-0.35, 2.43, 0.08]}
    />

    <slot {ref} />
  </Three>
{/if}
