<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\sakura1.gltf --transform -k
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

	const gltfUrl = new URL('$src/assets/models/trees/sakura1.gltf', import.meta.url).href
	const { gltf } = useGltf(gltfUrl,{useDraco:true})
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="sakuratree1_leaf"
      geometry={$gltf.nodes.sakuratree1_leaf.geometry}
      material={$gltf.nodes.sakuratree1_leaf.material}
      position={[0.74, 4.84, 2.49]}
    />
    <T.Mesh
      name="sakuratree1_leaf001"
      geometry={$gltf.nodes.sakuratree1_leaf001.geometry}
      material={$gltf.nodes.sakuratree1_leaf001.material}
      position={[2.37, 4.76, 1.02]}
    />
    <T.Mesh
      name="sakuratree1_leaf002"
      geometry={$gltf.nodes.sakuratree1_leaf002.geometry}
      material={$gltf.nodes.sakuratree1_leaf002.material}
      position={[-1.8, 3.86, 1.62]}
    />
    <T.Mesh
      name="sakuratree1_leaf003"
      geometry={$gltf.nodes.sakuratree1_leaf003.geometry}
      material={$gltf.nodes.sakuratree1_leaf003.material}
      position={[-2.12, 3.76, -0.18]}
    />
    <T.Mesh
      name="sakuratree1_leaf004"
      geometry={$gltf.nodes.sakuratree1_leaf004.geometry}
      material={$gltf.nodes.sakuratree1_leaf004.material}
      position={[0.47, 4.13, -3.1]}
    />
    <T.Mesh
      name="sakuratree1_leaf005"
      geometry={$gltf.nodes.sakuratree1_leaf005.geometry}
      material={$gltf.nodes.sakuratree1_leaf005.material}
      position={[-1.31, 3.52, -2.49]}
    />
    <T.Mesh
      name="sakuratree1_leaf006"
      geometry={$gltf.nodes.sakuratree1_leaf006.geometry}
      material={$gltf.nodes.sakuratree1_leaf006.material}
      position={[-0.74, 5.73, -0.75]}
    />
    <T.Mesh
      name="sakuratree1_branch006"
      geometry={$gltf.nodes.sakuratree1_branch006.geometry}
      material={$gltf.nodes.sakuratree1_branch006.material}
      position={[-0.84, 3.26, 0.66]}
    />
    <T.Mesh
      name="sakuratree1_branch001"
      geometry={$gltf.nodes.sakuratree1_branch001.geometry}
      material={$gltf.nodes.sakuratree1_branch001.material}
      position={[-0.88, 3.05, -0.22]}
    />
    <T.Mesh
      name="sakuratree1_branch002"
      geometry={$gltf.nodes.sakuratree1_branch002.geometry}
      material={$gltf.nodes.sakuratree1_branch002.material}
      position={[1.28, 4.03, 0.76]}
    />
    <T.Mesh
      name="sakuratree1_branch003"
      geometry={$gltf.nodes.sakuratree1_branch003.geometry}
      material={$gltf.nodes.sakuratree1_branch003.material}
      position={[-0.43, 3.13, -1.87]}
    />
    <T.Mesh
      name="sakuratree1_branch004"
      geometry={$gltf.nodes.sakuratree1_branch004.geometry}
      material={$gltf.nodes.sakuratree1_branch004.material}
      position={[0.24, 3.19, -1.31]}
    />
    <T.Mesh
      name="sakuratree1_branch005"
      geometry={$gltf.nodes.sakuratree1_branch005.geometry}
      material={$gltf.nodes.sakuratree1_branch005.material}
      position={[0.42, 3.91, 1.12]}
    />
    <T.Mesh
      name="sakuratree1_branch"
      geometry={$gltf.nodes.sakuratree1_branch.geometry}
      material={$gltf.nodes.sakuratree1_branch.material}
      position={[-0.1, 2.35, -0.03]}
    />

    <slot {ref} />
  </Three>
{/if}
