<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\tree0.gltf --transform -k
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

	const gltfUrl = new URL('$src/assets/models/trees/tree0.gltf', import.meta.url).href
	const { gltf } = useGltf(gltfUrl,{useDraco:true})
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="tree0_branch"
      geometry={$gltf.nodes.tree0_branch.geometry}
      material={$gltf.nodes.tree0_branch.material}
      position={[-0.5, 4.04, -0.22]}
    />
    <T.Mesh
      name="tree0_branch001"
      geometry={$gltf.nodes.tree0_branch001.geometry}
      material={$gltf.nodes.tree0_branch001.material}
      position={[-0.24, 5.17, -0.98]}
    />
    <T.Mesh
      name="tree0_branch002"
      geometry={$gltf.nodes.tree0_branch002.geometry}
      material={$gltf.nodes.tree0_branch002.material}
      position={[0.05, 4.72, 0.84]}
    />
    <T.Mesh
      name="tree0_branch003"
      geometry={$gltf.nodes.tree0_branch003.geometry}
      material={$gltf.nodes.tree0_branch003.material}
      position={[1.35, 5.15, 0.34]}
    />
    <T.Mesh
      name="tree0_branch004"
      geometry={$gltf.nodes.tree0_branch004.geometry}
      material={$gltf.nodes.tree0_branch004.material}
      position={[2.07, 5.54, -0.19]}
    />
    <T.Mesh
      name="tree0_leaf"
      geometry={$gltf.nodes.tree0_leaf.geometry}
      material={$gltf.nodes.tree0_leaf.material}
      position={[3.28, 7.25, -0.1]}
    />
    <T.Mesh
      name="tree0_leaf001"
      geometry={$gltf.nodes.tree0_leaf001.geometry}
      material={$gltf.nodes.tree0_leaf001.material}
      position={[0.32, 6.32, -3.1]}
    />
    <T.Mesh
      name="tree0_leaf002"
      geometry={$gltf.nodes.tree0_leaf002.geometry}
      material={$gltf.nodes.tree0_leaf002.material}
      position={[-2.47, 7.53, -0.79]}
    />
    <T.Mesh
      name="tree0_leaf003"
      geometry={$gltf.nodes.tree0_leaf003.geometry}
      material={$gltf.nodes.tree0_leaf003.material}
      position={[0.41, 7.63, 2.08]}
    />

    <slot {ref} />
  </Three>
{/if}
