<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\tree1.gltf --transform -k
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

	const gltfUrl = new URL('$src/assets/models/trees/tree1.gltf', import.meta.url).href
	const { gltf } = useGltf(gltfUrl,{useDraco:true})
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="tree1_branch"
      geometry={$gltf.nodes.tree1_branch.geometry}
      material={$gltf.nodes.tree1_branch.material}
      position={[-0.48, 3.9, -0.02]}
    />
    <T.Mesh
      name="tree1_branch003"
      geometry={$gltf.nodes.tree1_branch003.geometry}
      material={$gltf.nodes.tree1_branch003.material}
      position={[0.22, 4.84, -0.83]}
    />
    <T.Mesh
      name="tree1_branch002"
      geometry={$gltf.nodes.tree1_branch002.geometry}
      material={$gltf.nodes.tree1_branch002.material}
      position={[0.06, 4.73, 0.87]}
    />
    <T.Mesh
      name="tree1_branch004"
      geometry={$gltf.nodes.tree1_branch004.geometry}
      material={$gltf.nodes.tree1_branch004.material}
      position={[0.78, 4.55, -0.66]}
    />
    <T.Mesh
      name="tree1_leaf003"
      geometry={$gltf.nodes.tree1_leaf003.geometry}
      material={$gltf.nodes.tree1_leaf003.material}
      position={[2.71, 7.87, -0.22]}
    />
    <T.Mesh
      name="tree1_leaf002"
      geometry={$gltf.nodes.tree1_leaf002.geometry}
      material={$gltf.nodes.tree1_leaf002.material}
      position={[0.08, 5.96, -2.23]}
    />
    <T.Mesh
      name="tree1_leaf001"
      geometry={$gltf.nodes.tree1_leaf001.geometry}
      material={$gltf.nodes.tree1_leaf001.material}
      position={[-2.44, 7.49, -0.47]}
    />
    <T.Mesh
      name="tree1_leaf"
      geometry={$gltf.nodes.tree1_leaf.geometry}
      material={$gltf.nodes.tree1_leaf.material}
      position={[0.72, 5.95, 2.78]}
    />
    <T.Mesh
      name="tree1_leaf004"
      geometry={$gltf.nodes.tree1_leaf004.geometry}
      material={$gltf.nodes.tree1_leaf004.material}
      position={[-1.22, 8.72, 2.85]}
    />
    <T.Group name="tree1_branch001" position={[-0.02, 4.73, 1.5]}>
      <T.Mesh
        name="Cylinder010"
        geometry={$gltf.nodes.Cylinder010.geometry}
        material={$gltf.nodes.Cylinder010.material}
      />
      <T.Mesh
        name="Cylinder010_1"
        geometry={$gltf.nodes.Cylinder010_1.geometry}
        material={$gltf.nodes.Cylinder010_1.material}
      />
    </T.Group>
    <T.Mesh
      name="tree1_branch005"
      geometry={$gltf.nodes.tree1_branch005.geometry}
      material={$gltf.nodes.tree1_branch005.material}
      position={[0.9, 4.77, 0.18]}
    />
    <T.Group name="tree1_branch007" position={[-1.3, 4.96, 1.55]}>
      <T.Mesh
        name="Cylinder013"
        geometry={$gltf.nodes.Cylinder013.geometry}
        material={$gltf.nodes.Cylinder013.material}
      />
      <T.Mesh
        name="Cylinder013_1"
        geometry={$gltf.nodes.Cylinder013_1.geometry}
        material={$gltf.nodes.Cylinder013_1.material}
      />
    </T.Group>
    <T.Mesh
      name="tree1_branch006"
      geometry={$gltf.nodes.tree1_branch006.geometry}
      material={$gltf.nodes.tree1_branch006.material}
      position={[-1.48, 6, 3.22]}
    />
    <T.Mesh
      name="tree1_branch008"
      geometry={$gltf.nodes.tree1_branch008.geometry}
      material={$gltf.nodes.tree1_branch008.material}
      position={[-1.31, 5.93, 2.03]}
    />

    <slot {ref} />
  </Three>
{/if}
