<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\web\kuroneko\src\assets\models\tree2.gltf --transform -k
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

	const gltfUrl = new URL('$src/assets/models/trees/tree2.gltf', import.meta.url).href
	const { gltf } = useGltf(gltfUrl,{useDraco:true})
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="tree2_branch"
      geometry={$gltf.nodes.tree2_branch.geometry}
      material={$gltf.nodes.tree2_branch.material}
      position={[0.03, 3.37, -0.4]}
    />
    <T.Mesh
      name="tree2_branch001"
      geometry={$gltf.nodes.tree2_branch001.geometry}
      material={$gltf.nodes.tree2_branch001.material}
      position={[-0.06, 4.35, 0.68]}
    />
    <T.Mesh
      name="tree2_leaf"
      geometry={$gltf.nodes.tree2_leaf.geometry}
      material={$gltf.nodes.tree2_leaf.material}
      position={[0.28, 6.71, -1.73]}
    />
    <T.Mesh
      name="tree2_leaf001"
      geometry={$gltf.nodes.tree2_leaf001.geometry}
      material={$gltf.nodes.tree2_leaf001.material}
      position={[0.44, 7.44, 1.29]}
    />

    <slot {ref} />
  </Three>
{/if}
