<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\blends\planet\planet.gltf --transform -k
-->
<script lang="ts">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import type {BloomType} from "$lib/types"
  import { bloomObject } from '$lib/stores';
	import type { Group } from 'three';

	const gltfUrl = new URL('$src/assets/models/planet/planet.glb', import.meta.url).href
  const { gltf } = useGltf(gltfUrl, { useDraco: true })
  export let bloomType: BloomType = undefined
  let obj: Group
  $:{
    if(bloomType && obj){
      $bloomObject = [obj, bloomType]
    }
  }
</script>

{#if $gltf}
  <T.Group bind:ref={obj} {...$$restProps} name="planetbackup002" position={[-0.05, 3.07, -0.26]}>
    <T.Mesh name="Icosphere008" geometry={$gltf.nodes.Icosphere008.geometry} material={$gltf.materials.water} />
    <T.Mesh
      name="Icosphere008_1"
      geometry={$gltf.nodes.Icosphere008_1.geometry}
      material={$gltf.materials['deep water']}
    />
    <T.Mesh
      name="Icosphere008_2"
      geometry={$gltf.nodes.Icosphere008_2.geometry}
      material={$gltf.materials.deepdeepwater}
    />
    <T.Mesh name="Icosphere008_3" geometry={$gltf.nodes.Icosphere008_3.geometry} material={$gltf.materials.Snow} />
    <T.Mesh
      name="Icosphere008_4"
      geometry={$gltf.nodes.Icosphere008_4.geometry}
      material={$gltf.materials.semisnow}
    />
    <T.Mesh name="Icosphere008_5" geometry={$gltf.nodes.Icosphere008_5.geometry} material={$gltf.materials.grass} />
    <T.Mesh
      name="Icosphere008_6"
      geometry={$gltf.nodes.Icosphere008_6.geometry}
      material={$gltf.materials.grassside}
    />
  </T.Group>
{/if}
