<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 C:\Users\kuro\Desktop\blends\planet\planet.gltf --transform -k
-->
<script lang="ts">
  import { bloomObject } from '$lib/stores';
  import type { BloomType } from "$lib/types";
  import { useFrame, type Scale } from '@threlte/core';
  import { Vector3, type Group } from 'three';
  import Model from './Model.svelte';
	
  export let bloomType: BloomType = undefined
  export let rotate: boolean = false
  export let model: Group
  
	useFrame((_,delta)=>{
    update(delta)
	})

	function update(delta: number){
    let scale = 1000*delta
		if(rotate && model){
      model.rotateOnAxis(new Vector3(0,1,0),0.0001*scale)
    }
	}

  $:{
    if(bloomType && model){
      $bloomObject = [model, bloomType]
    }
  }
</script>
<Model {...$$restProps} bind:model={model}>
  <slot/>
</Model>
